---
title: "Reproducing the figures"
format: 
    html:
        embed-resources: true
---

## Load libraries

```{r}
#| output: false
library(Seurat)
library(ggplot2)
library(forcats)
library(qs)
library(sessioninfo)
```


## Figure 1

**UMAP of all cells (Figure 1B)**
```{r}
options(timeout = 3600)
if (!file.exists("umap_figure.qs")) {
    download.file(
        "https://zenodo.org/records/14226219/files/umap_figure.qs?download=1",
        "umap_figure.qs"
    )
}
umap_figure <- qread("umap_figure.qs")
DimPlot(
    umap_figure,
    reduction = "umap.scvi.full",
    pt.size = .1,
    alpha = .1,
    cols = umap_figure@misc$cluster_col,
    label = TRUE,
    raster = FALSE
) +
    NoLegend() +
    theme(
        axis.text = element_blank(),
        axis.ticks = element_blank()
    ) +
    xlab("UMAP_1") +
    ylab("UMAP_2")
```

## Figure 2

**UMAP immune cells (Figure 2A)**

```{r}
if (!file.exists("ic_figure.qs")) {
    download.file(
        "https://zenodo.org/records/14226219/files/umap_figure.qs?download=1",
        "ic_figure.qs"
    )
}
ic_figure <- qread("ic_figure.qs")
DimPlot(
    ic_figure,
    reduction = "umap.rpca",
    pt.size = .1,
    alpha = .3,
    cols = ic_figure@misc$ic_cluster_col,
    label = TRUE,
    raster = FALSE
) +
    theme(
        axis.text = element_blank(),
        axis.ticks = element_blank()
    ) +
    NoLegend() +
    xlab("UMAP1") +
    ylab("UMAP2")
```

**Feature plots immune cells (Figure 2B)**

```{r}
FeaturePlot(
    ic_figure,
    features = c("MS4A7", "CX3CR1", "TREM2", "LYVE1", "FOLR2", "TIMD4"),
    reduction = "umap.rpca",
    pt.size = 0.1,
    raster = FALSE,
    coord.fixed = TRUE,
    cols = c("#F0F0F0", "#CB181D"),
    order = TRUE,
    ncol = 3
) &
    theme(
        axis.text = element_blank(),
        axis.ticks = element_blank()
    ) &
    xlab("UMAP1") &
    ylab("UMAP2")

```

**Enrichment of gene ontology terms in  Macro 18 (Figure 2C)**

```{r}
#| fig-height: 3
if (!file.exists("enrichr_macro18.qs")) {
    download.file(
        "https://zenodo.org/records/14226219/files/umap_figure.qs?download=1",
        "b_plasma_figure.qs"
    )
}
enrichr_macro18 <- qread("enrichr_macro18.qs")
enrichr_macro18 |>
    dplyr::slice_min(order_by = Adjusted.P.value, n = 10, with_ties = FALSE) |>
    tidyr::separate(Overlap, into = c("overlap1", "overlap2")) |> # separate overlap in two columns
    dplyr::mutate(Term = gsub(x = Term, pattern = "\\s\\(.+\\)", replacement = "")) |>
    dplyr::mutate(overlap = as.numeric(overlap1) / as.numeric(overlap2)) |> # calculcate overlap
    ggplot(aes(y = reorder(Term, -log10(Adjusted.P.value)), x = -log10(Adjusted.P.value))) +
    geom_col(fill = scales::hue_pal()(5)[1]) +
    labs(
        x = "-Log10 Adjusted P value",
        y = ""
    ) +
    theme_classic() +
    theme(legend.position = "none")
```

**Dot plot IGH chain genes (Figure 2E)**
```{r}
if (!file.exists("ic_figure.qs")) {
    download.file(
        "https://zenodo.org/records/14226219/files/umap_figure.qs?download=1",
        "b_plasma_figure.qs"
    )
}
b_plasma_figure <- qread("b_plasma_figure.qs")
DotPlot(
    b_plasma_figure,
    features = c("IGHM", "IGHD", "IGHG1", "IGHG2", "IGHG3", "IGHG4", "IGHA1", "IGHA2"),
    scale = FALSE,
    dot.scale = 10
) +
    viridis::scale_color_viridis(option = "viridis") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, face = "italic")) +
    xlab("") +
    ylab("")
```

## Figure 3

**Abundance of clusters (Figure 3A)**
```{r}
#| fig-width: 3
#| fig-height: 3
if (!file.exists("propeller_PNP_CTRL.qs")) {
    download.file(
        "https://zenodo.org/records/14226219/files/umap_figure.qs?download=1",
        "propeller_PNP_CTRL.qs"
    )
}
if (!file.exists("propeller_PNP_CTRL.qs")) {
    download.file(
        "https://zenodo.org/records/14226219/files/umap_figure.qs?download=1",
        "propeller_PNP_CTRL_ic.qs"
    )
}
propeller_PNP_CTRL <- qread("propeller_PNP_CTRL.qs")
propeller_PNP_CTRL_ic <- qread("propeller_PNP_CTRL_ic.qs")

dotplotPropeller <- function(data, color) {
    ggplot(data, aes(x = log2ratio, y = fct_reorder(cluster, log2ratio), color = cluster)) +
        geom_point(size = 5) +
        theme_classic() +
        geom_vline(
            xintercept = 0, color = "red",
            linetype = "solid"
        ) +
        scale_color_manual(values = color) +
        xlab("Log2 fold change") +
        ylab(NULL) +
        theme(legend.position = "none")
}
dotplotPropeller(propeller_PNP_CTRL, color = umap_figure@misc$cluster_col)
dotplotPropeller(propeller_PNP_CTRL_ic, color = ic_figure@misc$ic_cluster_col)
```

## Session info

```{r}
session_info()
```